server:
  port: 8080
  servlet:
    context-path: /api/

spring:
  application:
    name: DOCKER-DEV-TRAINING-SERVICE
  data:
    mongodb:
      host: mongo
      port: 27017
      database: user-information-db
      uri: mongodb://myuser:mypassword@mongo:27017/user-information-db?authSource=admin
      auto-index-creation: true
      authentication-database: admin
management:
  endpoints:
    web:
      exposure:
        include: env,health,info
logging:
  level:
    root: INFO
    com.docker: INFO
    org.springframework: INFO