server:
  servlet:
    contextPath: /api/
  port: 8080

spring:
  application:
    name: DOCKER-DEV-TRAINING-SERVICE
    version: 1.0.0
  profiles:
    active: local
  data:
    mongodb:
      maxMongoPoolConnectionIdleTimeInSeconds: 60
      uri: mongodb://mongo:27017/user-information-db
      database: user-information-db
      auto-index-creation: false
      max-pool-size: 5

logging:
  level:
    root: INFO
    com.docker: INFO
    org.springframework: INFO

