server:
  servlet:
    contextPath: /api/
  port: 8080

spring:
  application:
    name: DOCKER-DEV-TRAINING-SERVICE
    version: 1.0.0
  profiles:
    active: docker
  data:
    mongodb:
      maxMongoPoolConnectionIdleTimeInSeconds: 60
      database: user-information-db
      auto-index-creation: false
      max-pool-size: 5
      uri: mongodb://myuser:mypassword@mongo:27017/user-information-db?authSource=admin

logging:
  level:
    root: INFO
    com.docker: INFO
    org.springframework: INFO

