FROM amazoncorretto:17
LABEL maintainer="RajatSharma"

# Set working directory
WORKDIR /app

# Create a volume for logs
VOLUME ["/app/logs"]

# Copy the built JAR file
COPY target/*.jar /app/app.jar

# Expose the application port
EXPOSE 8080

# Set the default active Spring profile (can be overridden at runtime)
ENV SPRING_PROFILES_ACTIVE=default

# Run the application
ENTRYPOINT ["java", "-jar", "/app/app.jar"]
CMD ["--spring.profiles.active=${SPRING_PROFILES_ACTIVE}"]