version: "3.8"

services:
  mongo:
    image: mongo:6.0.17
    hostname: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=myuser
      - MONGO_INITDB_ROOT_PASSWORD=mypassword
      - MONGO_INITDB_DATABASE=user-information-db
    volumes:
      - mongo-data:/data/db
    command: [ "--bind_ip", "0.0.0.0" ]
    healthcheck:
      test: >
        mongosh --host mongo --port 27017
        -u "myuser" -p "mypassword"
        --authenticationDatabase admin --quiet
        --eval 'db.adminCommand({ ping: 1 }).ok' | grep -q 1 || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - app-network

  backend:
    image: rajatsharma04/docker-training-be:1.0.1
    restart: unless-stopped
    depends_on:
      mongo:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATA_MONGODB_URI=mongodb://myuser:mypassword@host.docker.internal:27017/user-information-db?authSource=admin
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s
    networks:
      - app-network

  frontend:
    image: rajatsharma04/docker-training-fe:1.0.1
    restart: unless-stopped
    depends_on:
      backend:
        condition: service_healthy
    ports:
      - "3000:80"
    environment:
      - API_BASE_URL=http://backend:8080/api/
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data: