version: '3.8'
services:
  mongo:
    image: mongo:6
    environment:
      MONGO_INITDB_ROOT_USERNAME: myuser
      MONGO_INITDB_ROOT_PASSWORD: mypassword
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/user-information-db --username myuser --password mypassword --authenticationDatabase admin --quiet
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "27017:27017"
    networks:
      - app-network

  backend:
    image: rajatsharma04/docker-training-be:1.0.0
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://myuser:mypassword@mongo:27017/user-information-db?authSource=admin
    depends_on:
      mongo:
        condition: service_healthy
    restart: on-failure
    ports:
      - "8080:8080"
    networks:
      - app-network

  frontend:
    image: rajatsharma04/docker-training-fe:1.0.0
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
